### ISSUE TITLE
help me please!!!

### ISSUE THREAD

**Issue by DDmitriy** [litecoin-foundation/loafwallet-ios-deprecated#47]
Hello everybody!

I sent from my wallet loafwallet 25 litcoine to Poloniex

It's been 2 weeks already !! money never came

Please tell me how to get my litcoine back ???

Sent with LTTynPFtm9jW2nRBMnRETGWHiVw4N9gWLg

to the wallet LfbegCc16cpQaRAv1L7YBiSBDPKYC5o9VC

confirmed in block 1331230

Very much I ask to help !!

**Comment by losh11** [comment]
You sent to Lfb...?

https://insight.litecore.io/address/LfbegCc16cpQaRAv1L7YBiSBDPKYC5o9VC Says
that you’ve already spent your coins.

**Comment by DDmitriy** [comment]
I posted on 13 December    25 litcoine

but in this purse

and spent another summer in 17 litcoine
this is an old transaction

**Comment by DDmitriy** [comment]
they get to another wallet? could it be scammers?

**Comment by losh11** [comment]
Email contact@loafwallet.org with all issues in detail + screenshot.

**Comment by DDmitriy** [comment]
Ok

**Comment by DDmitriy** [comment]
The developers do not answer, many have the same problem with this purse, what other ways to return the money?

**Comment by DDmitriy** [comment]
support loafwallet does not work since August 2017

How now to return my litecoin ??

**Comment by losh11** [comment]
Hey it’s christmas man. Your not going to get an instant reply. I’ll try to
answer ASAP.

**Comment by DDmitriy** [comment]
Thank you so much
and with Christmas you

**Comment by losh11** [comment]
Hey,

I don't see any email from anyone called Dmitriy, can you make sure to
email contact@loafwallet.org please?

Thanks,
Loshan

**Comment by DDmitriy** [comment]
I wrote c mail d.dobrosvet@icloud

today sent another email with Emil d.dobrosvet@gmail.com

Waiting for an answer from you
Thank you !

**Comment by DDmitriy** [comment]
Thank you very much, there was no problem, this is my inattention
